### ISSUE TITLE
NoMethodError in Spree::CheckoutController#skrill_return 

### ISSUE THREAD

**Issue by nicwn** [spree-contrib/spree_skrill#4]
Dev env on local box. Mac 10.7, Ruby 1.9.3-p125, Rails 3.2.3, Spree 1.1.0.rc1

Created mock product, payment method with Skrill, shipping method. Try to go through purchasing the product.

Successfully reached http://localhost:3000/orders/R523551828/checkout/edit?state=payment page, choose Skrill as payment, login with my test user's name & password, check "Pay from my balance ...", click Confirm

Payment goes through, money debited from account, receive email "Send money confirmation" from moneybookers.com, but...

Error:

```
NoMethodError in Spree::CheckoutController#skrill_return

undefined method `authorize' for #<Spree::BillingIntegration::Skrill::QuickCheckout:0x007f8675c09330>

Rails.root: /Users/nick/Sites/work_projects/maki-spree

activemodel (3.2.3) lib/active_model/attribute_methods.rb:407:in `method_missing'
activerecord (3.2.3) lib/active_record/attribute_methods.rb:148:in `method_missing'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/payment/processing.rb:107:in `block in gateway_action'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/payment/processing.rb:147:in `protect_from_connection_error'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/payment/processing.rb:104:in `gateway_action'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/payment/processing.rb:22:in `authorize!'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/payment/processing.rb:11:in `process!'
activerecord (3.2.3) lib/active_record/associations/collection_proxy.rb:89:in `each'
activerecord (3.2.3) lib/active_record/associations/collection_proxy.rb:89:in `method_missing'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/order.rb:367:in `process_payments!'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/app/models/spree/order.rb:95:in `block (2 levels) in <class:Order>'
state_machine (1.1.2) lib/state_machine/eval_helpers.rb:77:in `call'
state_machine (1.1.2) lib/state_machine/eval_helpers.rb:77:in `evaluate_method'
state_machine (1.1.2) lib/state_machine/callback.rb:191:in `block in run_methods'
state_machine (1.1.2) lib/state_machine/callback.rb:190:in `each'
state_machine (1.1.2) lib/state_machine/callback.rb:190:in `run_methods'
state_machine (1.1.2) lib/state_machine/callback.rb:159:in `call'
state_machine (1.1.2) lib/state_machine/transition.rb:413:in `before'
state_machine (1.1.2) lib/state_machine/transition.rb:239:in `block in run_callbacks'
state_machine (1.1.2) lib/state_machine/transition.rb:341:in `block in pausable'
state_machine (1.1.2) lib/state_machine/transition.rb:341:in `catch'
state_machine (1.1.2) lib/state_machine/transition.rb:341:in `pausable'
state_machine (1.1.2) lib/state_machine/transition.rb:239:in `run_callbacks'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:126:in `run_callbacks'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:211:in `run_callbacks'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:63:in `catch'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:63:in `block in perform'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:185:in `within_transaction'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:62:in `perform'
state_machine (1.1.2) lib/state_machine/integrations/active_model.rb:520:in `around_validation'
activesupport (3.2.3) lib/active_support/callbacks.rb:310:in `_callback_around_327'
activesupport (3.2.3) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_957'
activesupport (3.2.3) lib/active_support/callbacks.rb:403:in `_run__2000211521846883198__validation__1638450746808088729__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
activemodel (3.2.3) lib/active_model/validations/callbacks.rb:53:in `run_validations!'
activemodel (3.2.3) lib/active_model/validations.rb:179:in `valid?'
activerecord (3.2.3) lib/active_record/validations.rb:69:in `valid?'
activerecord (3.2.3) lib/active_record/validations.rb:77:in `perform_validations'
activerecord (3.2.3) lib/active_record/validations.rb:50:in `save'
activerecord (3.2.3) lib/active_record/attribute_methods/dirty.rb:22:in `save'
activerecord (3.2.3) lib/active_record/transactions.rb:241:in `block (2 levels) in save'
activerecord (3.2.3) lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
activerecord (3.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.2.3) lib/active_record/transactions.rb:208:in `transaction'
activerecord (3.2.3) lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
activerecord (3.2.3) lib/active_record/transactions.rb:241:in `block in save'
activerecord (3.2.3) lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
activerecord (3.2.3) lib/active_record/transactions.rb:240:in `save'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:153:in `block (2 levels) in run_actions'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:153:in `each'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:153:in `block in run_actions'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:169:in `catch_exceptions'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:147:in `run_actions'
state_machine (1.1.2) lib/state_machine/transition_collection.rb:60:in `perform'
state_machine (1.1.2) lib/state_machine/transition.rb:212:in `perform'
state_machine (1.1.2) lib/state_machine/event.rb:167:in `fire'
state_machine (1.1.2) lib/state_machine/event.rb:236:in `block in add_actions'
state_machine (1.1.2) lib/state_machine/machine.rb:753:in `call'
state_machine (1.1.2) lib/state_machine/machine.rb:753:in `block (2 levels) in define_helper'
state_machine (1.1.2) lib/state_machine/event.rb:241:in `block in add_actions'
state_machine (1.1.2) lib/state_machine/machine.rb:753:in `call'
state_machine (1.1.2) lib/state_machine/machine.rb:753:in `block (2 levels) in define_helper'
spree_skrill (1.0.1) app/controllers/spree/checkout_controller_decorator.rb:19:in `skrill_return'
actionpack (3.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.3) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.3) lib/active_support/callbacks.rb:491:in `_run__3009483273498695205__process_action__2843202716152929239__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.3) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.3) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
activerecord (3.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.3) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.3) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.3) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.3) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.3) lib/journey/router.rb:68:in `block in call'
journey (1.0.3) lib/journey/router.rb:56:in `each'
journey (1.0.3) lib/journey/router.rb:56:in `call'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:600:in `call'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/lib/spree/core/middleware/redirect_legacy_product_url.rb:13:in `call'
/Users/nick/.rvm/gems/ruby-1.9.3-p125@maki-spree/bundler/gems/spree-71ac94ea37ba/core/lib/spree/core/middleware/seo_assist.rb:27:in `call'
railties (3.2.3) lib/rails/engine.rb:479:in `call'
railties (3.2.3) lib/rails/railtie/configurable.rb:30:in `method_missing'
journey (1.0.3) lib/journey/router.rb:68:in `block in call'
journey (1.0.3) lib/journey/router.rb:56:in `each'
journey (1.0.3) lib/journey/router.rb:56:in `call'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:600:in `call'
warden (1.1.1) lib/warden/manager.rb:35:in `block in call'
warden (1.1.1) lib/warden/manager.rb:34:in `catch'
warden (1.1.1) lib/warden/manager.rb:34:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.1) lib/rack/etag.rb:23:in `call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.3) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `_run__41027189138784901__call__1638450746808088729__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.3) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.3) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.3) lib/rails/engine.rb:479:in `call'
railties (3.2.3) lib/rails/application.rb:220:in `call'
rack (1.4.1) lib/rack/content_length.rb:14:in `call'
railties (3.2.3) lib/rails/rack/log_tailer.rb:14:in `call'
thin (1.3.1) lib/thin/connection.rb:80:in `block in pre_process'
thin (1.3.1) lib/thin/connection.rb:78:in `catch'
thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:53:in `process'
thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
thin (1.3.1) lib/thin/server.rb:159:in `start'
rack (1.4.1) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.1) lib/rack/server.rb:265:in `start'
railties (3.2.3) lib/rails/commands/server.rb:70:in `start'
railties (3.2.3) lib/rails/commands.rb:55:in `block in <top (required)>'
railties (3.2.3) lib/rails/commands.rb:50:in `tap'
railties (3.2.3) lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'

Request

Parameters:

{"payment_method_id"=>"1",
 "token"=>"ce316235f2217970",
 "transaction_id"=>"R523551828",
 "msid"=>"90407C0EFB1CC6593C74B308021A8CB5",
 "order_id"=>"R523551828"}
```

**Comment by nicwn** [comment]
Note that prior to this, I was experiencing the typical Rails 3.2.3 mass assignment errors.

After signing in to Skrill and choosing to pay with account balance and click Confirm, I got:

```
ActiveModel::MassAssignmentSecurity::Error in Spree::CheckoutController#skrill_return

Can't mass-assign protected attributes: source, payment_method

Rails.root: /Users/nick/Sites/work_projects/maki-spree
```

I fixed that by creating a payment_decorator.rb file in app/models/

```
Spree::Payment.class_eval do
  attr_accessible :source, :payment_method
end
```

which fixed that problem and brought me to this new error.

Thanks.

**Comment by radar** [comment]
Does this still break with the 1.1 release?

**Comment by GeekOnCoffee** [comment]
@cloneofsnake I've been able to verify that in the 1.1 release using a credit card number works in test mode. Can you validate that this issue still exists for you?

**Comment by pongy** [comment]
Still having the same issue with 1.1 release.
And it looks the same as the one happened in the spree_paypal_express gem:
https://github.com/spree/spree_paypal_express/issues/48

**Comment by radar** [comment]
@pongy Could you please submit a patch to fix this issue?
